spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bankuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bankpass}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
